[package]
name = "lsr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.16"
chrono = "0.4"
tabular = "0.1.4"
users = "0.11"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
rand = "0.8"

