[package]
name = "tailr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.16"
num = "0.4"
regex = "1"
once_cell = "1"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
rand = "0.8"
