[package]
name = "treer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.16"
walkdir = "2"
regex = "1"
users = "0.11"
chrono = "0.4.39"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
rand = "0.8"
